[package]
name = "DevBase-website-Actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
sqlx = { version = "0.8.2", features = ["postgres"] }




[profile.release]
debug = false
[profile.dev]
debug = 1